//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkManager.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LinkManager.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style=&apos;font-family: &quot;Times New Roman&quot;, Times, serif; font-size: 17px; border-collapse: collapse;width: 100%;&apos;&gt;&lt;thead&gt;&lt;tr&gt;&lt;th style=&apos;text-align: center;padding: 8px;background-color: #4CAF50;color: white;&apos;&gt;Supervisor&lt;/th&gt;&lt;th style=&apos;text-align: center;padding: 8px;background-color: #4CAF50;color:white;&apos;&gt;Project&lt;/th&gt;&lt;th style=&apos;text-align: center;padding: 8px;background-color: #4CAF50;color: white;&apos;&gt;SelfCost&lt;/th&gt;&lt;th style=&apos;text-align: center;padding: 8px;background-color: #4CAF50;color: white;&apos;&gt;Proposed  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RiskEstimatesTableHeader {
            get {
                return ResourceManager.GetString("RiskEstimatesTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr style=&apos;background-color: {0}&apos;&gt;&lt;td style=&apos;text-align: center;padding: 8px;&apos;&gt;{1}&lt;/td&gt;&lt;td style=&apos;text-align: center;padding: 8px;&apos;&gt;{2}&lt;/td&gt;&lt;td style=&apos;text-align: center;padding: 8px;&apos;&gt;{3}&lt;/td&gt;&lt;td style=&apos;text-align: center;padding: 8px;&apos;&gt;{4}&lt;/td&gt;&lt;td style=&apos;text-align: center;padding: 8px;&apos;&gt;{5}&lt;/td&gt;&lt;/tr&gt;.
        /// </summary>
        internal static string RiskEstimatesTableRow {
            get {
                return ResourceManager.GetString("RiskEstimatesTableRow", resourceCulture);
            }
        }
    }
}
